### ISSUE TITLE
Compatibility issue with Bukkit Conversation API

### ISSUE THREAD

**Issue by PikaMug** [WiIIiam278/HuskChat#102]
Seeking input for https://github.com/PikaMug/Quests/issues/1594 (which affects both HuskChat and now-outdated BungeeChat).

With HuskChat installed on a Bungee server and [Quests](https://www.spigotmc.org/resources/quests.3711/) installed on a Spigot/Paper server, it is not possible to hold a conversation. For example, using _/quests editor_ and selecting option 1 will prompt the user to enter a name. This typically works fine, but HuskChat seems to override the functionality and simply displays the reply in chat. This does not occur on Bungee servers without HuskChat installed.

**Comment by WiIIiam278** [comment]
Please see the docs on [backend chat entry](https://william278.net/docs/huskchat/backend-chat-entry), which explains why this happens with some plugins. Plugins using chat for input on the backend for non-chat functions are relying on a bad practice that goes against the API spec, so you may wish to relay this to the dev.

**Comment by PikaMug** [comment]
Appreciate your input. We do have an alternative using commands, but it's only been necessary for restoring clickable components on 1.19 servers—regular chat input works fine regardless. I sympathize with the idea that, today, using chat for input is not ideal, but back when Quests was started the Conversation API was the only option for longer strings. Considering Bukkit/Spigot continues to support the API, I would not consider it bad practice, and fail to see where the specification says otherwise.

It's my opinion that HuskChat and related plugins should be making a greater effort to respect the Conversation API, as regular ol' Bungeecord chat is fully compatible. However, I'll link to your comment and consider the matter closed. Thank you.

**Comment by WiIIiam278** [comment]
Thanks for your comment back, I totally do understand the issue. My understanding of the conversation api was more that it was intended for chat related purposes rather than *input* into a system -- I.e aiding conversations between players :) however, I do appreciate that practically this distinction not particularly important. The argument of text limits is a novel one, as the footprint of the command entry (reducing the maximum input by three characters for a simple one letter command), this wasn't something I'd previously considered. 

Is having the full 255 characters of space a requirement here? If it is, that's totally valid and understandable, I'm just slightly surprised. Of course, the need to rewrite is no small feat and I absolutely appreciate that this use case may not be worth it on balance.

There's really nothing I as a chat plugin developer can do here. No code I write here is being run on the backends; there's simply no way for me to magically inform the backend as the system by nature has to cancel chat messages to prevent duplicate messages appearing on the backend server. 

To that end, I provide the passthrough channel options to allow for this to still work in cases where it's a must. There are cases where backend plugins do need to see chat, perhaps for logging or DiscordSRV integration, and you'd install a cancel-chat plugin on the backend.

With that all said, taking a step back: this is really a rather ridiculous thing, isn't it?! The solution is obvious: just use a backend chat plugin! HuskChat was built to be a simple - albeit fairly flexible - solution for cross server chat on a proxy; an alternative to the burden of more complex but feature rich backend solutions (good for simpler more vanilla x-server experiences) and so I do think it's better to evaluate whether a different solution would be better if your use case depends on more complex backend plugins and setups
