### ISSUE TITLE
Plugins which require chat input are not compatible with HuskChat

### ISSUE THREAD

**Issue by farum12** [WiIIiam278/HuskChat#83]
It has been observed, that any plugin (verified with CommandPanels and BankPlus), which requires chat input is not compatible with HuskChat. Input from the chat is completely ignored.

**Preconditions:**
- HuskChat installed
- any plugin that requires chat input, eg. BankPlus (https://www.spigotmc.org/resources/%E2%9C%A8-bankplus-%E2%9C%A8.93130/) installed
- op account

**Repro Steps:**
1. Login to the server.
2. Type /bank.
3. Click Deposit-Custom.
4. Type the amount of money to deposit.
5. Observe the issue as the number is ignored.

**Comment by TrueWinter** [comment]
Due to HuskChat being a proxy plugin and handling chat on the proxy, it is incompatible with plugins that require chat input.

However, there is a workaround. HuskChat has channel scopes which allow you to select how a message is handled. Create a new channel, setting it up with the `PASSTHROUGH` broadcast scope. Players on your server can then use the following steps to interact with plugins that require chat input:

1. Switch to the passthrough channel (`/channel <channel id>` or the channel's shortcut command, if configured)
2. Type `/bank` (or whichever command requires chat input), etc.
3. Type the amount in chat
4. Switch back to the channel the player was chatting in earlier (by default, this is the `global` channel which can be used by typing `/g`)

**Comment by WiIIiam278** [comment]
^^ 
Please check our dedicated documentation page for more on this matter: https://william278.net/docs/huskchat/Backend-Chat-Entry
